module(name = "vcpkg_hellos")

bazel_dep(name = "platforms", version = "1.0.0")
bazel_dep(name = "rules_cc", version = "0.1.4")
bazel_dep(name = "rules_vcpkg", version = "0.0.0")
local_path_override(
    module_name = "rules_vcpkg",
    path = "../..",
)

vcpkg = use_extension("@rules_vcpkg//vcpkg:extensions2.bzl", "vcpkg")
vcpkg.bootstrap(
    lockfile = "//:rules_vcpkg_lock.json",
    release = "2025.09.17",
    sha256 = "f9977705bd29970e38d3d52af6475ec1de03de0d613f37191394b12345349d14",
)
vcpkg.install(package = "boost-asio")
use_repo(vcpkg, "vcpkg", "vcpkg_bootstrap")
