set(VCPKG_TARGET_ARCHITECTURE %%ARCH_SHORT%%)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)

set(VCPKG_CMAKE_SYSTEM_NAME %%SYSTEM_NAME%%)

set(X_VCPKG_BUILD_GNU_LIBICONV 1)

string(APPEND VCPKG_C_FLAGS " -D__DATE__=\"redacted\"")
string(APPEND VCPKG_C_FLAGS " -D__TIMESTAMP__=\"redacted\"")
string(APPEND VCPKG_C_FLAGS " -D__TIME__=\"redacted\"")

string(APPEND VCPKG_CXX_FLAGS " -D__DATE__=\"redacted\"")
string(APPEND VCPKG_CXX_FLAGS " -D__TIMESTAMP__=\"redacted\"")
string(APPEND VCPKG_CXX_FLAGS " -D__TIME__=\"redacted\"")

set(VCPKG_DETECTED_CMAKE_C_COMPILER "%%CXX_COMPILER%%")
set(VCPKG_DETECTED_CMAKE_CXX_COMPILER "%%CXX_COMPILER%%")

set(VCPKG_CHAINLOAD_TOOLCHAIN_FILE toolchain.cmake)
